### ISSUE TITLE
Capstone_The_True_DJ Top 100

### ISSUE THREAD

**Issue by CoderMarkus** [CoderMarkus/capstone_true100#1]
**Value Proposition**

As a user
I want to see the true DJ Top 100
So i can hear the best music

![Image](https://user-images.githubusercontent.com/124438709/229450709-1e2cc2d4-95be-413b-b5de-4cbfbde843be.png)

** Acceptance Criteria**

- [ ] all tracks are displayed in a list
- [ ] a header with headline is displayed
- [ ] tracks are sorted by counts of playing

**Tasks**

- [ ] Selection of data source(s) for the Top 100 list, e.g. a proprietary database.
- [ ] Development of an algorithm to rate songs based on criteria such as number of counts of playing.

**Complexity**

XXL

**Comment by toshydev** [comment]
The interface implementation seems like an extra user story since it makes the initial list component unnecessarily complex. 
Same with the algorithm.

**Comment by CoderMarkus** [comment]
Thanks for your reply. I deleted this task. I will implement it later.

**Comment by ella-blaupause** [comment]
Your tasks are too general, try to keep them smaller.

My suggestion for Value Proposition:
As an user
I want to see a list of ...
so that I can get an overview of ...

and then you can start with a small task like data fetching
