### ISSUE TITLE
 Capstone_The_True_DJ Top 100 #2

### ISSUE THREAD

**Issue by CoderMarkus** [CoderMarkus/capstone_true100#3]
**Value Proposition**

As a DJ, I want to be able to upload my tracks to the Top 100 DJ list easily, so that the most played music can be featured and potentially gain more exposure to a wider audience.

![Image](https://user-images.githubusercontent.com/124438709/232694722-de71d006-c588-4efa-a483-17bcffeb99b2.png)

**Acceptance Criteria**

- [ ] The upload button should be prominently displayed on the Top 100 DJ list interface, and clearly labeled as "Upload Playlist".

- [ ] Clicking on the upload button should open a dialog box that allows the user to select the playlistfile they want to upload.

- [ ] The upload dialog box should display a progress bar or other indicator to show the user that the upload is in progress.

**Tasks**

- [ ] Design the interface for the upload button and upload dialog box, and incorporate it into the existing Top 100 DJ list interface.

- [ ] Implement the backend logic to handle file uploads and validation of the uploaded file format.

- [ ] Implement a progress bar or other indicator to show the user that the upload is in progress.

**Complexity**

XL

**Comment by liebeckm** [comment]
Hey @CoderMarkus , what an interesting App. I'm looking forward to see more :) Here are my suggestions:
1. Add a Excalidraw Screenshot for the dialogue box for better understanding
2. do you want to upload whole playlists or also only choosen songs? Maybe you can make that more clear within the Screenshot or in acceptance criteria.
3. Building the page, building the dialogue box and the progress bar could also be seperated into different user stories, because doing all of this could be quite extensive

**Comment by AnjaSiewert** [comment]
I agree with the comment above, but LGTM, go for it 💪🏼💪🏼
