### ISSUE TITLE
Capstone_The_True_DJ Top 100 #3

### ISSUE THREAD

**Issue by CoderMarkus** [CoderMarkus/capstone_true100#5]
**Value Proposition**

As a user i want a good and simple and good ui/navigation/design experience so that i can use the app easily.

**Acceptance Criteria**

- [ ] The navigation elements must be clearly recognizable and highlighted with color.
- [ ] The colors should be attractive and easy to distinguish.
- [ ] The navigation elements should function equally well on desktop and mobile devices.
- [ ] The navigation elements should be clearly distinguishable from other elements on the page.
- [ ] The navigation should have a clear hierarchy and be logically structured.

**Tasks**

- [ ]  Choosing appropriate colors that are easy to recognize and visually appealing.
- [ ]  Verifing that the navigation elements function equally well on desktop and mobile devices.
- [ ]  Developing a consistent style for the navigation elements that is clearly distinguishable from other elements on the page.
- [ ]  Creating a clear hierarchy for the navigation and logically arrange the navigation elements.
- [ ]  Testing the navigation on various devices and verify that it meets the requirements.

**Complexity**

M

**Comment by BenRodProd** [comment]
LGTM, but you repeated "good" in the value proposition...
